version: 2.0
jobs:
  build:
    machine:
      image: circleci/classic:latest
    branches:
          only:
            - master
    steps:
      - run:
          name: Install LFTP
          command: |
            sudo apt-get update;
            sudo apt-get install lftp;
      - checkout
      - run:
          name: Send Via SFTP
          command: lftp ftp://dev@dev.bibikids.vn@dev.bibikids.vn -e "mirror -v -R ./ ./test; quit"

