version: 2.0
jobs:
  build:
    machine:
      image: circleci/classic:latest
    branches:
          only:
            - master
    steps:
      - run:
          name: Install LFTP
          command: |
            sudo apt-get update;
            sudo apt-get install lftp;
      - checkout
      - run:
          name: Send Via SFTP
          command: |
           lftp ftp://${FTP_USER}:${FTP_PWD}@${FTP_LOCATION}
           set ssl:verify-certificate no
           ls
           mirror -v -R --exclude .git/ --exclude .circleci/ --exclude vendor/ --exclude update/ --exclude node_modules/ --exclude install/ --exclude files/ --exclude .vscode/R /home/circleci/project /test
           quit
